### ISSUE TITLE
Dream Balls not available after Knuckle Badge - Resolved

### ISSUE THREAD

**Issue by Mutalyx** [BuffelSaft/pokeemerald#185]
Checking in the pokemon centres after defeating Brawly and all items besides the dream balls have appeared.

**Comment by BuffelSaft** [comment]
Are you on version 1.3?

**Comment by Mutalyx** [comment]
Yep! Just downloaded and started yesterday.

**Comment by Mutalyx** [comment]
Starting to think that I may have updated to the wrong file. Going to speed through another copy and check for myself, so here's a heads up that this may be a mistake on my end!

**Comment by Mutalyx** [comment]
Issue was user error. Time to go and properly name my files. Sorry for the false alarm!

**Comment by BuffelSaft** [comment]
Ah ok, no worries!
