### ISSUE TITLE
Bronzor Evolution Level

### ISSUE THREAD

**Issue by Mutalyx** [BuffelSaft/pokeemerald#191]
(This is whilst playing on version 1.3)
I have passed level 33 with Bronzor and have not seen a prompt for evolution. I read through the documents and saw no mention of a change to evolution level, so I thought that I would mention it here just in case this was an oversight.

**Comment by BuffelSaft** [comment]
It's been set to 35 for some reason, I'll fix it. Thanks for letting me know!

**Comment by BuffelSaft** [comment]
Fixed!
