### ISSUE TITLE
Pressing select in battle opens some kind of debugger?

### ISSUE THREAD

**Issue by adnanberberovic** [BuffelSaft/pokeemerald#195]
Hey, I accidentally pressed Select during a battle and a debug menu opened where you could change all sorts of properties on your current pokemon, like moves, stats, stat changes, status condition, even substitute health. I'm running version 1.3.1 of Inclement Emerald. I can record if needed but should be easy to test it. You press select when the menu where you choose Fight/Bag/Pokemon/Run is active.

**Comment by BuffelSaft** [comment]
Thanks for the bug report! I accidentally left debug on when building the patch; 1.3.1 is a bit of a mess. Will have 1.4 ready tomorrow to clean it up!

**Comment by BuffelSaft** [comment]
Fixed!
