### ISSUE TITLE
Parabolic charge drains less than half HP

### ISSUE THREAD

**Issue by adnanberberovic** [BuffelSaft/pokeemerald#205]
As opposed to the move tooltip, which says "Damages adjacent Pokémon and heals up by **half** of it". The most recent example I can provide is the following:

The enemy was lvl 52, Golduck from Picknicker Becky in the desert. Parabolic Charge OHKO:d the Golduck, but only restored 39 HP, which means if the tooltip was correct, the Golduck would have 78 HP total, however that's too low for a level 52 Golduck.

**Comment by BuffelSaft** [comment]
Ah that one's a text error, Parabolic Charge was changed to do more damage but steal less HP as a trade off. Will update the move description.
