### ISSUE TITLE
Swimmer Jerome has (probably) incorrect level modifier

### ISSUE THREAD

**Issue by adnanberberovic** [BuffelSaft/pokeemerald#206]
`static const struct TrainerMonItemCustomMoves sParty_Jerome[] = {
    {
    .lvl = -2,
    .species = SPECIES_BARBARACLE,
    .spread = SPREAD_31_IV_60_EV,
    .moves = MOVE_RAZOR_SHELL, MOVE_STRENGTH, MOVE_NIGHT_SLASH, MOVE_CROSS_CHOP
    },
    {
    .lvl = -22,
    .species = SPECIES_BEARTIC,
    .spread = SPREAD_31_IV_60_EV,
    .moves = MOVE_ICICLE_CRASH, MOVE_LIQUIDATION, MOVE_THRASH, MOVE_CHARM
    }
}`

Beartic has a level modifier of -22, should probably be -2.

**Comment by BuffelSaft** [comment]
Yeah that's definitely meant to be -2. Thanks for the detailed bug report!
