### ISSUE TITLE
Cloud Nine Ability Non-functional

### ISSUE THREAD

**Issue by jopahoward** [BuffelSaft/pokeemerald#279]
When using a Pokemon with the Cloud Nine ability, the effects of weather from drought do not disappear, even though the text box stating "The effects of weather disappeared" occurs.

![image](https://user-images.githubusercontent.com/46663713/139961676-3d863703-7809-4141-aba6-60429899965a.png)
[save.zip](https://github.com/BuffelSaft/pokeemerald/files/7464397/save.zip)

**Comment by BuffelSaft** [comment]
Are you sure? What effects didn't disappear? It doesn't actually remove the weather, just its effects

**Comment by jopahoward** [comment]
Specifically, I noted a one-turn Solarbeam from Flannery, but I am now less sure, as I clearly misunderstood the effects of the ability. If it is something that is only in effect while the Pokemon is on the field, then that is my mistake

**Comment by jopahoward** [comment]
I looked into it more and it seems that it is indeed only active when the Pokemon is on the field. My mistake, sorry for wasting your time!

**Comment by BuffelSaft** [comment]
No problem!
