### ISSUE TITLE
Link Battle

### ISSUE THREAD

**Issue by Oseanic** [BuffelSaft/pokeemerald#286]
The Link Battle works but it just suddenly lags really heavily once it starts. I'm not sure if it's a Emulator Issue or something else (I'm using My Boy Emulator linked to another device using the same version of game and Emulator).

**Comment by BuffelSaft** [comment]
I don't know either, try with a different game and see if that lags too.

**Comment by kleeenexfeu** [comment]
> The Link Battle works but it just suddenly lags really heavily once it starts. I'm not sure if it's a Emulator Issue or something else (I'm using My Boy Emulator linked to another device using the same version of game and Emulator).

It all depends by what you mean by "lags really heavily". The games have to sync, so it's definitely slower than normal gameplay, even on cartridge. If I remember well, trade/link battle even set automatically the text speed to slow, to avoid issue. And of course, using speed button may cause issues for the reason mentioned.
From the experience I had, it indeed lags, but just like a cartridge would do in link.

**Comment by Oseanic** [comment]
I just didn't do enough testing. Apparently link Via Bluetooth is a lot faster than linking through Wifi (which for some reason is making the game lag so much on my case might differ from others). Link related stuff works just fine. Sorry to waste everyones time >_< .
