### ISSUE TITLE
good project

### ISSUE THREAD

**Issue by Logan-1991** [BuffelSaft/pokeemerald#304]
It is a good project, I like it, there is a mistake with the ability speed boost it is not activated with blaziken, and it is not tested with others.

**Comment by BuffelSaft** [comment]
I assume Impulse is Speed Boost in another language? And what do you mean by it is not activated?

**Comment by Logan-1991** [comment]
I have a blaziken but I don't see the effect of the speed boost skill, many opponents overtake it and break it.
Adding that it is a great rom in fact for me it is the best very well balanced the difficulty is great. You are a genius thank you.
