### ISSUE TITLE
 Correction.

### ISSUE THREAD

**Issue by Logan-1991** [BuffelSaft/pokeemerald#311]
Correction. I have a blaziken but I don't see the effect of the speed boost skill, many opponents overtake it and break it.also the hidden ability antidote of Gliscor instead of heal, it subtracts Hp
Adding that it is a great rom in fact for me it is the best very well balanced the difficulty is great. Excellent work you are a genius thank you.

**Comment by BuffelSaft** [comment]
Do you definitely have those abilities on those Pokemon? They're both working correctly on my end.
Thanks, glad you're enjoying it!

**Comment by Logan-1991** [comment]
the antidote ability is hidden in Gliscor but with toxic orb it poisoned it but it does not work I did the same with breelom and if it works and the same happens with blaziken it does not activate impulse I tried it in other emulators but the result is the same.
