### ISSUE TITLE
A small suggestion.

### ISSUE THREAD

**Issue by YamiKamui** [BuffelSaft/pokeemerald#319]
> Hey BuffelSalt! Firstly I wanted to say thanks for the awesome game! I have been having a great time playing it. I would like to make a suggestion about Shedinja. I think the buff it received to its attack stats was very nice, but it would be great if it was given the move Entrainment for double battles strats in a future update! That's all I wanted to say so once again thank you for the incredible game!

**Comment by BuffelSaft** [comment]
Thanks! That sounds incredibly broken haha, will have to say no to that one!

**Comment by YamiKamui** [comment]
That's fina.Thank you anyways.

Em sáb., 11 de dez. de 2021 21:56, BuffelSaft ***@***.***>
escreveu:
