### ISSUE TITLE
Shelly's Mega Beedrill AI bug

### ISSUE THREAD

**Issue by Keyacom** [BuffelSaft/pokeemerald#329]
Shelly's Mega Beedrill used Poison Jab on Gliscor, even though it knows Drill Peck as well. Gliscor's Ground typing makes it resist Poison. Drill Peck would do more damage.
![InclementEmerald_1645566981664.png](https://user-images.githubusercontent.com/70766223/155226520-9fc91865-3291-4887-9189-5e5027408cc1.png)

**Comment by Raptors13** [comment]
They actually do the same amount of damage due to it having adaptability. The AI is more than likely choosing randomly between the three moves that are able to hit Gliscor since they all do the same damage.
