### ISSUE TITLE
Will Hisui new pokemon/forms will be available in the future updates?

### ISSUE THREAD

**Issue by AbreuEfechou** [BuffelSaft/pokeemerald#337]
**These includes:**

_Regional variant_
* Hisuian Growlithe and Hisuian Arcanine
* Hisuian Voltorb and Electrode
* Hisuian Typhlosion
* Hisuian Qwilfish and his new evolution Overqwil
* Hisuian Sneasel and his new evolution Sneasler
* Hisuain Samurott
* Hisuain Lilligant
* Hisuian Zorua and Hisuian Zoroark
* Hisuian Braviary
* Hisuain Sligoo and Goodra
* Hisuain Avalugg
* Hisuain Decidueye

_New forms_
* Origin Dialga
* Origin Palkia

_New Pokémon_
* Kleavor
* Ursaluna
* Basculegion
* Sneasler
* Overqwil
* Enamorus

I know it's a lot of work, but would be awesome to have a game with every pokémon to date

**Comment by BuffelSaft** [comment]
This is for issues, not questions. This one has been answered several times already in the PC thread and is in the FAQ.
