### ISSUE TITLE
Pokeblocks do not work

### ISSUE THREAD

**Issue by PokeGamerGuy** [BuffelSaft/pokeemerald#340]
As soon as you select your berry in the berry mixer the game glitches out and freezes.Sometimes it distorts the image and sometimes it doesn't.

**Comment by BuffelSaft** [comment]
Duplicate of #112. Already fixed for the next version fortunately!

**Comment by LimeAndry7** [comment]
but it isn't fixed! I have the latest 1.13 version and still have this bug. Berry blender just freezes the game after you select the berry
