### ISSUE TITLE
Inclement Emerald as basis for fan game

### ISSUE THREAD

**Issue by space-bass** [BuffelSaft/pokeemerald#356]
Hello! I'm unsure if this is the right place to post this, but I'm working on an original Pokemon game (new region, new pokemon, etc) and would like it to be a ROM hack - Gen 3 seems like the best place to do so, since gen 5 would necessitate an absurd amount of visual work (animated sprites...) and there are very few tools on hacking gen 4. I played through Inclement Emerald a few months ago and it is seriously the best experience I've ever had in Pokemon. 

This is all, inevitably, buildup to my question: could I obtain permission to use Inclement Emerald as a basis for my ROM hack? The updated mechanics would be amazing to have in our fan game. Thank you :)

**Comment by BuffelSaft** [comment]
Hey, glad you enjoyed Inclement! You can use IE as a base for a ROM hack if you want; it's open source after all! That said, I'd strongly recommend using the [RHH expansion project](https://github.com/rh-hideout/pokeemerald-expansion) as a base instead. That's where Inclement gets its modern mechanics from, but as it's a few hundred PRs ahead now it's a _lot_ less buggy and has more features (e.g. Z-moves, more gen 8 stuff).

It'd be a lot less work to port features from IE into a fresh RHH project than it would be to merge the latest RHH branch into this version of IE.
